name: build

on: [push, pull_request]

jobs:
  build-dart-latest:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get

    - uses: axel-op/dart-package-analyzer/with-full-sdk@v2
      id: analysis # set an id for the current step
      with:
        githubToken: ${{secrets.GITHUB_TOKEN}}
        # You can then use this id to retrieve the outputs in the next steps.
        # The following step shows how to exit the workflow with an error if a score is below 100:
    - name: Check scores
      # NB: "analysis" is the id set above. Replace it with the one you used if different.
      run: |
        MAINTENANCE_SCORE=${{ steps.analysis.outputs.maintenance }}
        HEALTH_SCORE=${{ steps.analysis.outputs.health }}
        if (( $(echo "$MAINTENANCE_SCORE < 100" | bc) )) || (( $(echo "$HEALTH_SCORE < 100" | bc) ))
        then
          echo "Scores are not both equal to 100"
          exit 1
        fi

# https://github.com/marketplace/actions/dart-flutter-package-analyzer
# https://github.com/axel-op/github_actions_toolkit.dart
# https://github.com/actions/toolkit

  build-dart-2-8:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.8.4

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub downgrade
    - name: Run dartanalyzer
      run: dartanalyzer --fatal-warnings --fatal-infos --fatal-lints bin/ lib/ test/
    - name: Run tests
      run: pub run test
